### ISSUE TITLE
"Could not post comment : GD does not appear to be avaliable …" 

### ISSUE THREAD

**Issue by remyslab** [tomas-samot/PrivateBin-docker#1]
Hi, 
GD extension seems miss, it's impossible to post comments when the option is activate.
Error display : "Could not post comment : GD does not appear to be avaliable …" 
Thank!
Edit : I fixed it #2

**Comment by tomas-samot** [comment]
This is now fixed. #2 
Thank you for pointing this out. I never used the comments section so never came across this issue.
